<a href="https://colab.research.google.com/github/Ananyaaaa23/ml/blob/main/mlassignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 6 3 2 1]


In [ ]:
import numpy as np
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array1 = array1.flatten()
print(flattened_array1)


[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array = array1.ravel()
print(flattened_array)


[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

elementwise_comparison = arr1 == arr2
print(elementwise_comparison)


[[ True  True]
 [ True  True]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

same_object = arr1 is arr2
print(same_object)


False


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
counts = np.bincount(x)
most_frequent_value = np.argmax(counts)
indices = np.where(x == most_frequent_value)[0]
print("Most frequent value in x:", most_frequent_value)
print("Indices of the most frequent value in x:", indices)


Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]


In [ ]:
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
counts = np.bincount(y)
most_frequent_value = np.argmax(counts)
indices = np.where(y == most_frequent_value)[0]
print("Most frequent value in y:", most_frequent_value)
print("Indices of the most frequent value in y:", indices)

Most frequent value in y: 1
Indices of the most frequent value in y: [0 1 2]


In [ ]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = np.sum(gfg)
print("Sum of all elements:", total_sum)
row_wise_sum = np.sum(gfg, axis=1)
print("Sum of elements row-wise:", row_wise_sum)
column_wise_sum = np.sum(gfg, axis=0)
print("Sum of elements column-wise:", column_wise_sum)

Sum of all elements: 45
Sum of elements row-wise: [[14]
 [16]
 [15]]
Sum of elements column-wise: [[20  9 16]]


In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diagonal_sum = np.trace(n_array)
print("Sum of diagonal elements:", diagonal_sum)
eigenvalues, _ = np.linalg.eig(n_array)
print("Eigenvalues of the matrix:", eigenvalues)
_, eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors of the matrix:\n", eigenvectors)
inverse_matrix= np.linalg.inv(n_array)
print("Inverse of the matrix:\n", inverse_matrix)

Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
result_i = np.dot(p, q)
print("Matrix Multiplication Result (i):")
print(result_i)
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
result_ii = np.dot(p, q)
print("Matrix Multiplication Result (ii):")
print(result_ii)
p_flat = p.flatten()
q_flat = q.flatten()
data = np.vstack((p_flat, q_flat))
cov_matrix = np.cov(data, bias=True)
print("Covariance Matrix (i):")
print(cov_matrix)
p_flat = p.flatten()
q_flat = q.flatten()
data = np.vstack((p_flat, q_flat))
cov_matrix = np.cov(data, bias=True)
print("Covariance Matrix (ii):")
print(cov_matrix)


Matrix Multiplication Result (i):
[[16 19]
 [26 31]]
Matrix Multiplication Result (ii):
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance Matrix (i):
[[1.80555556 0.19444444]
 [0.19444444 4.47222222]]
Covariance Matrix (ii):
[[1.80555556 0.19444444]
 [0.19444444 4.47222222]]


In [ ]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
x_flat = x.flatten()
y_flat = y.flatten()
inner_product = np.dot(x_flat, y_flat)
outer_product = np.outer(x_flat, y_flat)
xx, yy = np.meshgrid(x_flat, y_flat, indexing='ij')
cartesian_product = np.stack([xx, yy], axis=-1)
print("Inner Product:")
print(inner_product)
print("\nOuter Product:")
print(outer_product)
print("\nCartesian Product:")
print(cartesian_product)


Inner Product:
79

Outer Product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product:
[[[ 2  1]
  [ 2  5]
  [ 2  0]
  [ 2  5]
  [ 2 10]
  [ 2  3]]

 [[ 3  1]
  [ 3  5]
  [ 3  0]
  [ 3  5]
  [ 3 10]
  [ 3  3]]

 [[ 4  1]
  [ 4  5]
  [ 4  0]
  [ 4  5]
  [ 4 10]
  [ 4  3]]

 [[ 3  1]
  [ 3  5]
  [ 3  0]
  [ 3  5]
  [ 3 10]
  [ 3  3]]

 [[ 2  1]
  [ 2  5]
  [ 2  0]
  [ 2  5]
  [ 2 10]
  [ 2  3]]

 [[ 9  1]
  [ 9  5]
  [ 9  0]
  [ 9  5]
  [ 9 10]
  [ 9  3]]]


In [ ]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])
absolute_values = np.abs(array)
print("Element-wise Absolute Value:")
print(absolute_values)
flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
percentiles_column = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
print("\n25th, 50th, and 75th Percentiles (Flattened):")
print(percentiles_flattened)
print("\n25th, 50th, and 75th Percentiles (Each Column):")
print(percentiles_column)
print("\n25th, 50th, and 75th Percentiles (Each Row):")
print(percentiles_row)
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)
mean_column = np.mean(array, axis=0)
median_column = np.median(array, axis=0)
std_column = np.std(array, axis=0)
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("\nMean, Median, and Standard Deviation (Flattened):")
print(f"Mean: {mean_flattened}")
print(f"Median: {median_flattened}")
print(f"Standard Deviation: {std_flattened}")
print("\nMean, Median, and Standard Deviation (Each Column):")
print(f"Mean: {mean_column}")
print(f"Median: {median_column}")
print(f"Standard Deviation: {std_column}")
print("\nMean, Median, and Standard Deviation (Each Row):")
print(f"Mean: {mean_row}")
print(f"Median: {median_row}")
print(f"Standard Deviation: {std_row}")
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)
print("\nFloor Values:")
print(floor_values)
print("\nCeiling Values:")
print(ceiling_values)
print("\nTruncated Values:")
print(truncated_values)
print("\nRounded Values:")
print(rounded_values)


Element-wise Absolute Value:
[[1 2 3]
 [4 5 6]]

25th, 50th, and 75th Percentiles (Flattened):
[-3.5 -0.5  2.5]

25th, 50th, and 75th Percentiles (Each Column):
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

25th, 50th, and 75th Percentiles (Each Row):
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean, Median, and Standard Deviation (Flattened):
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Mean, Median, and Standard Deviation (Each Column):
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Mean, Median, and Standard Deviation (Each Row):
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]

Floor Values:
[-2. -2. -1.  0.  1.  1.  3.]

Ceiling Values:
[-1. -1. -0.  1.  2.  2.  3.]

Truncated Values:
[-1. -1. -0.  0.  1.  1.  3.]

Rounded Values:
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Sorted Array:")
print(sorted_array)
indices_sorted = np.argsort(array)
print("\nIndices of Sorted Array:")
print(indices_sorted)
four_smallest = np.partition(array, 4)[:4]
print("\n4 Smallest Elements:")
print(np.sort(four_smallest))
five_largest = np.partition(array, -5)[-5:]
print("\n5 Largest Elements:")
print(np.sort(five_largest))
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array.astype(int) == array]
print("\nInteger Elements Only:")
print(integer_elements)
float_elements = array[array.astype(int) != array]
print("\nFloat Elements Only:")
print(float_elements)


Sorted Array:
[ 10  16  16  52  54  62 453]

Indices of Sorted Array:
[0 3 4 1 5 2 6]

4 Smallest Elements:
[10 16 16 52]

5 Largest Elements:
[ 16  52  54  62 453]

Integer Elements Only:
[1. 2. 3. 2.]

Float Elements Only:
[1.2 2.2]


In [ ]:
pip install numpy matplotlib pillow


In [ ]:
from PIL import Image
import numpy as np
def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)
    if img.mode == 'RGB':
        filename = path.rsplit('.', 1)[0] + '_rgb.txt'
        np.savetxt(filename, img_array.reshape(-1, 3), fmt='%d', delimiter=',')
    elif img.mode == 'L':
        filename = path.rsplit('.', 1)[0] + '_gray.txt'
        np.savetxt(filename, img_array.reshape(-1), fmt='%d', delimiter=',')
    else:
        raise ValueError("Unsupported image mode: {}".format(img.mode))
    print(f"Image data saved to {filename}")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def load_and_display_image(filename, is_rgb=True):
    data = np.loadtxt(filename, delimiter=',', dtype=int)

    if is_rgb:
        height = int(np.sqrt(data.shape[0] / 3))
        width = data.shape[0] // (3 * height)
        img_array = data.reshape((height, width, 3))
    else:
        side = int(np.sqrt(data.shape[0]))
        img_array = data.reshape((side, side))
    plt.imshow(img_array, cmap='gray' if not is_rgb else None)
    plt.axis('off')
    plt.show()